# Generated by Django 4.0.3 on 2022-03-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
        migrations.RemoveField(
            model_name='place',
            name='created',
        ),
        migrations.AddField(
            model_name='games',
            name='game_type',
            field=models.IntegerField(choices=[(1, 'RTS'), (2, 'FPS'), (3, 'MOBA'), (4, 'Other')], default=4),
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(default=4, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
