# Generated by Django 4.0.3 on 2022-03-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_app', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ManyToManyField(to='yt_app.team'),
        ),
    ]
