# Generated by Django 4.0.3 on 2022-03-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_app', '0004_match_team1'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ManyToManyField(to='yt_app.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ManyToManyField(related_name='Team1', to='yt_app.team'),
        ),
    ]
