# Generated by Django 4.0.3 on 2022-03-31 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yt_app', '0006_remove_match_tournament_remove_match_team1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='match_field',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yt_app.match'),
        ),
    ]
