# Generated by Django 4.0.3 on 2022-04-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_app', '0008_duel_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.IntegerField(choices=[(1, 'RTS'), (2, 'FPS'), (3, 'MOBA'), (4, 'Other')], default=4)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='tournaments',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='online',
        ),
        migrations.AddField(
            model_name='tournament',
            name='place',
            field=models.ManyToManyField(to='yt_app.place'),
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.ManyToManyField(to='yt_app.game'),
        ),
    ]
