# Generated by Django 4.0.3 on 2022-04-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_app', '0010_alter_game_game_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='user',
            new_name='players',
        ),
    ]
